#!/bin/bash
cp Makefile.t Makefile
list=
for f in level_*.c; do
	code=$(sed -n 's/^[ \t]*LEVEL_CODE[ \t]*([ \t]*"\([^"]*\)".*/\1/p' "$f")
	[[ -z $code ]] && continue
	list="$list $code.so"

	objs=($(sed -n 's/^[ \t]*#[ \t]*include[ \t]\+"\([^.]*\)\.h".*/\1.o/p' "$f"))
	libs=()
	grep -q '^[ \t]*#[ \t]*include[ \t]\+<math\.h>.*' "$f" && libs+=(-lm)

	echo "$code.so: ${f%.c}.o" "${objs[@]}"
	echo '	gcc $(LDFLAGS) -o $@ $+' "${libs[@]}"
	echo
done >> Makefile
echo "all2:$list" >> Makefile
